const express = require("express");
const userRouter = require("./user.js");
import createUserRoutes from "./user.js";
const { createCourseRoutes } = require("./course.js");
app.use(express.json());
app.use("/user", userRouter);
app.use("/course", courseRouter);
createUserRoutes(app);
createCourseRoutes(app);
app.listen(3000);
